//
//  MKWebViewPerfConstant.m
//  MixKit
//
//  Created by liang on 2021/6/15.
//

#import "MKWebViewPerfConstant.h"

NSString *const PERF_KEY_MATCH_MESSAGE_PARSER = @"PERF_KEY_MATCH_MESSAGE_PARSER";
NSString *const PERF_KEY_INVOKE_CALLBACK_FUNC = @"PERF_KEY_INVOKE_CALLBACK_FUNC";
NSString *const PERF_KEY_FORMAT_CALLBACK_SCRIPT = @"PERF_KEY_FORMAT_CALLBACK_SCRIPT";
NSString *const PERF_KEY_INVOKE_NATIVE_METHOD = @"PERF_KEY_INVOKE_NATIVE_METHOD";
NSString *const PERF_KEY_CONVERT_NATIVE_ARGUMENTS = @"PERF_KEY_CONVERT_NATIVE_ARGUMENTS";
