//
//  MKSocketPerfConstant.m
//  MoonBridge
//
//  Created by liang on 2021/6/23.
//

#import "MKSocketPerfConstant.h"

NSString *const PERF_KEY_SOCKET_MATCH_MESSAGE_PARSER = @"PERF_KEY_SOCKET_MATCH_MESSAGE_PARSER";
NSString *const PERF_KEY_SOCKET_INVOKE_CALLBACK_FUNC = @"PERF_KEY_SOCKET_INVOKE_CALLBACK_FUNC";
NSString *const PERF_KEY_SOCKET_INVOKE_NATIVE_METHOD = @"PERF_KEY_SOCKET_INVOKE_NATIVE_METHOD";
